{% extends "templates/item_page.html" %}
{% set namespaces = "cmoon::test" %}
{% set library_name = "Testing" %}
{% set item_name = "assert_throws" %}
{% block nested %}../{% endblock %}
{% block content2 %}
{{macros.defined("cmoon.test", github_url_src + "/test/test.ixx")}}
{{macros.overload_set([
'
template<class Exception, class F, class... Args>
void assert_throws(F&& callable, std::string_view message, Args&&... args, const std::source_location& location = std::source_location::current());
',
'
template<class Exception, class F, class... Args>
void assert_throws(F&& callable, Args&&... args, const std::source_location& location = std::source_location::current());
'
])}}
<p>
    Throws an <code><a href="assert_exception/index.html">assert_exception</a></code> if an exception of type <code>Exception</code> is not thrown.
</p>
{{macros.function_stats(
    [["callable", "Function to call with <code>args...</code>"],
     ["args", "Arguments to be forwarded to the given function"],
     ["message", "Extra information to be added to the error message"],
     ["location", "Information about where in the file this assertion was ran"]],
    "",
    "",
    ""
)}}
{{macros.example_code(
'
import <stdexcept>;

import cmoon.test;

void will_throw(int)
{
    throw std::runtime_error{"Exception thrown!"};
}

class example_test : public cmoon::test::test_case
{
    public:
        example_test()
            : cmoon::test::test_case{"example test"} {}

        void operator()() override
        {
            cmoon::test::assert_throws<std::runtime_error>(will_throw, 5);
        }
};
'
)}}
{% endblock %}